# Masukkan semua file cpp Anda
OBJS = oop.cpp main.cpp piranha.cpp akuarium.cpp bendaHidup.cpp bendaMati.cpp guppy.cpp ikan.cpp koin.cpp makanan.cpp siput.cpp controller.cpp

CC = g++
COMPILER_FLAGS = -std=c++11 -Wall -O2
LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf
OBJ_NAME = oopquarium
all :
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
